$(function(){$("#oomframe").dialog({autoOpen:false,draggable:false,resizable:false,show:"clip",hide:"clip",speed:"fast",width:790});$("#maincontent").accordion({autoHeight:false,navigation:true,collapsible:false,animated:"bounceslide"});$("#expChart").mousemove(function(a){a=$("#expChart").offset().top-a.pageY;updateFromChart(a)})});
function updateFromChart(a){var b="java";a>275&&a<=305&&(b="php");a>245&&a<=275&&(b="javascript");a>215&&a<=245&&(b="mysql");a>185&&a<=215&&(b="ajax");a>155&&a<=185&&(b="json");a>125&&a<=155&&(b="jquery");a>95&&a<=125&&(b="csharp");a>65&&a<=95&&(b="ror");a>35&&a<=65&&(b="perl");a<=35&&(b="jsp");setSliders(b)}function displayFull(a){var b=$("#"+a).html();$("#projectdetails").html(b);$("h2.projtitle").removeClass("whiteonblue").addClass("blueonwhite");$("#"+a+"heading").addClass("whiteonblue")}
function openSummary(){$("#maincontent").accordion("activate",0)}
$(document).ready(function(){$.gchart.setDefaults({backgroundColor:"#e1e2ea",titleColor:"#081530"});$("#sourceChart").gchart({type:"pie",title:"Experience distribution",pieOrientation:108,legend:"right",legendColor:"#081530",legendSize:16,extension:{chdl:"work|school|personal"},series:[$.gchart.series("Source",[33,133,34],["#f5f50a","#00c400","#c40000"])]});$("#expChart").gchart({type:"barHorizGrouped",title:"Experience amount|(relative to Java)",margins:15,axes:[$.gchart.axis("left","jsp,perl,ror,c#,jquery,json,ajax,mysql,javascript,php,java".split(","),
"#081530",16)],series:[$.gchart.series("Amount",[100,85,95,90,85,75,80,15,25,20,30],"#8c9fdc")]});displayFull("oomtxt")});function oom(){$("#oomframe").dialog("open")}
function updateChart(a,b,c,d){setTimeout(function(){$("#sourceChart").gchart("change","pieOrientation",b)},25);$("#sourceChart").gchart("change","series",[$.gchart.series("Source",[a,b,c],["#f5f50a","#00c400","#c40000"])]);a="#8c9fdc,#8c9fdc,#8c9fdc,#8c9fdc,#8c9fdc,#8c9fdc,#8c9fdc,#8c9fdc,#8c9fdc,#8c9fdc,#8c9fdc".split(",");a[d]="#173db9";$("#expChart").gchart("change","series",[$.gchart.series("Amount",[100,85,95,90,85,75,80,15,25,20,30],a)])}
function setSliders(a){var b=[];a=="java"&&(b=[10,35,55,0]);a=="php"&&(b=[60,0,40,1]);a=="javascript"&&(b=[35,20,45,2]);a=="mysql"&&(b=[45,10,45,3]);a=="ajax"&&(b=[35,20,45,4]);a=="json"&&(b=[50,15,35,5]);a=="jquery"&&(b=[45,5,50,6]);a=="csharp"&&(b=[0,0,100,7]);a=="ror"&&(b=[80,0,20,8]);a=="perl"&&(b=[0,97,3,9]);a=="jsp"&&(b=[0,25,75,10]);updateChart(b[0],b[1],b[2],b[3]);$(".langtech").css("color","#8c9fdc");$("#"+a).css("color","#173db9");$("#summarytxt").html(getSummary(a))}
function getSummary(a){var b="";a=="java"&&(b="My schooling is focused largely on Java, and it's also used extensively in various personal trading applications, though only slightly at work");a=="php"&&(b="For web based projects this is my most often used server side language, particularly at work due to ease of deployment");a=="javascript"&&(b="JavaScript will probably be the most important language of the next decade, I've been using it more powerfully with each new project so they feel more like an app and less like a web page");
a=="csharp"&&(b="Primarily used C# to create an automated trading application that could easily interact with my brokerage's API. This was eventually abandoned in favor of a Java app using the FIX protocol");a=="ror"&&(b="My first app put into production was written in RoR (later re-written in PHP).  I wasn't crazy about RoR, but I will say <a href='http://railsforzombies.org/' target='_blank'><span class='atext'>Rails for Zombies</span></a> is by far the most entertaining way to learn a language");
a=="perl"&&(b="Thus far used almost entirely for school with only the occasional non-academic use");a=="jsp"&&(b="I love Java, so I was excited to expirement with JSP, but sadly I haven't had the opportunity  to work with it on a large sized project yet");a=="mysql"&&(b="Nearly every project I've worked on has involved utlizing a MySQL database");a=="ajax"&&(b="AJAX is used in nearly everything web related I code, it's a critical tool to go from web-page to web-app");a=="json"&&(b="Given the choice I use JSON whenever possible, except in the rare cases where using XML would offer a significant benefit");
a=="jquery"&&(b="A lot of my earlier JavaScript work was done without the aid of a framework.  Eventually I played around with both Dojo and jQuery before deciding jQuery was the better choice");return b};
